language: python

python:
  - "2.7"
  # - "3.5"

before_install:
  - pip install --upgrade pytest

install:
  - pip install -e .
  - pip install -e '.[test]'
  - pip install codecov
  - cp ci/testsettings.py testsettings.py
  - python -c "import uuid; print('SECRET_KEY = \'%s\'' % uuid.uuid4())" >> testsettings.py

script:
  - py.test --cov=annotator_store

after_success:
  - codecov
